config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'
  get 'messages/sent'

  get 'home/index'
  root :to => 'home#index' 

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'users/index'
  get 'users/show'
  get '/users/:id', :to => 'users#show', :as => :user
  get 'like' => 'users#like'
  get 'unlike' => 'users#unlike'

  get 'activities/index'
  get 'activities/user'

  resources :comments
  resources :posts
  resources :friendships
  resources :messages
  resources :contacts

  resources :gchats, only: [:new, :create, :index]
  get 'gchats/new'
  
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	
	default_scope -> { order('created_at DESC') }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
  	@users = User.all
  end

  def new
    @message = Message.new
    @recv_uid = params[:recv_uid]
  end

  def show
    @message = Message.where(:receiver_user_id => current_user.id).group_by {|m| m.user_id}
  end

  def sent
    @sentmessage = Message.where(:user_id => current_user.id).group_by {|m| m.receiver_user_id}
  end

  def create
    @message = Message.new(message_params)
    @message.user = current_user

    respond_to do |format|
      if @message.save
        format.html { redirect_to root_url, notice: 'Message was sent successfully.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end
 
  private

  def message_params
    params.require(:message).permit(:message, :user_id, :receiver_user_id)
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<div class="container-fluid main-container">
<%= render "layouts/sidenav" %>
<div class="col-md-10 content">

<h2 class="page-header">New Message</h2>

<div class="row col-md-8 custyle">
    <table class="table table-striped custab">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th class="text-center">Action</th>
        </tr>
    </thead>

<% for user in @users %>
  <% if current_user.id != user.id %>

            <tr>
                <td><%= user.name.humanize %></td>
                <td><%= user.email %></td>
                <td class="text-center">
                <%= link_to '<span class="glyphicon glyphicon-edit"></span> New Message'.html_safe,new_message_path(:recv_uid=> user.id ) %>
                </td>
            </tr>
 
  <% end %>
<% end %>

</table>
    </div>

</div>
</div>

app/views/messages/new.html.erb
<div class="container-fluid main-container">
<%= render "layouts/sidenav" %>
<div class="col-md-10 content">

<h2 class="page-header">New Message</h2>

<%= form_for :message, url: messages_path do |f| %>
        
        <br style="clear:both">
            <div class="form-group col-md-4 ">                                
                <textarea required="true" name="message[message]" value="<%= @message.message %>"class="form-control input-sm " type="textarea" id="message" placeholder="Message" maxlength="140" rows="7"></textarea>
                    <span class="help-block"><p id="characterLeft" class="help-block ">You have reached the limit</p></span>                    
            </div>
        <br style="clear:both">
        <div class="form-group col-md-2">
        <button class="form-control input-sm btn btn-success disabled" id="btnSubmit" name="btnSubmit" type="submit" style="height:35px"> Send</button>    
    </div>

    <%= f.hidden_field :receiver_user_id, :value => @recv_uid %>
    <%= f.hidden_field :user_id %>
  
<% end %>

</div>
</div>

app/views/messages/sent.html.erb
<div class="container-fluid main-container">
<%= render "layouts/sidenav" %>
<div class="col-md-10 content">

<h2 class="page-header">Sent Messages</h2>

<% @sentmessage.each do |key, value| %>

  <div class="row">
    <div class="col-md-8">
        <section class="comment-list">
          <!-- First Comment -->
          <article class="row">
            
            <div class="col-md-9 col-sm-10">
              <div class="panel panel-default arrow right">
                <div class="panel-body">
                <% value.each do |m| %>
                  <header class="text-right">
                    <time class="comment-date"><i class="fa fa-clock-o"></i> <%= time_ago_in_words(m.created_at) %> ago | <%= m.created_at.to_time.to_formatted_s(:db) %> </time>
                  </header>
                  <div class="comment-post">
                    <p class="text-right">
                      <%= m.message %>
                    </p>
                  </div>
                <% end %>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-sm-2 hidden-xs">
              <figure class="thumbnail">
                <% value.each do |m| %>
                  <% @id = m.receiver_user_id %>
                <% end %>
                  <% user = User.find_by_id(@id) %> 
                  <% if user == nil || user == "" %>
                  <% elsif user.avatar? %>
                  <%= image_tag(user.avatar_url, :width => 50, :height => 50) %>
                  <% else %>
                  <%= image_tag(user.gravatar_url, :width => 50, :height => 50) %>
                  <% end %>
                <figcaption class="text-center">       
                  <% if user == nil || user == "" %>   
                    <i>(user left)</i>
                  <% else %>
                       <%= link_to user.name, user %>
                  <% end %>
                </figcaption>
              </figure>
            </div>
          </article>
        </section>
    </div>
   </div>

<% end %>

</div>
</div>

app/views/messages/show.html.erb
<div class="container-fluid main-container">
<%= render "layouts/sidenav" %>
<div class="col-md-10 content">

<h2 class="page-header">Received Messages</h2>

<% @message.each do |key, value| %>
   <div class="row">
    <div class="col-md-8">
        <section class="comment-list">
          <!-- First Comment -->
          <article class="row">
            <div class="col-md-3 col-sm-2 hidden-xs">
              <figure class="thumbnail">
                  <% value.each do |m| %>
                    <% @id = m.user_id %>
                  <% end %>
                  <% user = User.where(:id => @id) %>
                  <% user.each do |i| %>
                    <% if i.avatar? %>
                      <%= image_tag(i.avatar_url, :width => 50, :height => 50) %>
                    <% else %>
                      <%= image_tag(i.gravatar_url, :width => 50, :height => 50) %>
                    <% end %>
                    <figcaption class="text-center">       
                      <%= link_to i.name, i %>
                    </figcaption>
                <% end %>
              </figure>
            </div>
            <div class="col-md-9 col-sm-10">
              <div class="panel panel-default arrow left">
                <div class="panel-body">
                <%= link_to '<div class="pull-right"> <span class="glyphicon glyphicon-share"></span> Reply</div>'.html_safe,new_message_path(:recv_uid => @id ) %>
                <% value.each do |m| %>
                  <header class="text-left">
                    <time class="comment-date"><i class="fa fa-clock-o"></i> <%= time_ago_in_words(m.created_at) %> ago | <%= m.created_at.to_time.to_formatted_s(:db) %> </time>
                  </header>
                  <div class="comment-post">
                    <p class="text-left">
                      <%= m.message %>
                    </p>
                  </div>
                <% end %>
                </div> 
              </div>
            </div>
          </article>
        </section>
    </div>
   </div>

<% end %>

</div>
</div>