config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'
  get 'messages/sent'

  get 'home/index'
  root :to => 'home#index' 

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'users/index'
  get 'users/show'
  get '/users/:id', :to => 'users#show', :as => :user
  get 'like' => 'users#like'
  get 'unlike' => 'users#unlike'

  get 'activities/index'
  get 'activities/user'

  resources :comments
  resources :posts
  resources :friendships
  resources :messages
  resources :contacts

  resources :gchats, only: [:new, :create, :index]
  get 'gchats/new'
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	resourcify
	
	belongs_to :post
	belongs_to :user

	include PublicActivity::Model
	tracked owner: ->(controller, model) { controller && controller.current_user }
	 
	acts_as_likeable

	default_scope -> { order('created_at ASC') }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    redirect_to root_url
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    redirect_to root_url
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    redirect_to root_url
  end

  # GET /comments/1/edit
  def edit
    @comment = current_user.comments.find(params[:id])
    redirect_to root_url
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        @comment.create_activity :create, owner: current_user
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to :back, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    #@comment = current_user.comments.find(params[:id])
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :post_id, :user_id)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>

<article class="timeline-entry">
    
    <div class="timeline-entry-inner">
      <time class="timeline-time" ><span><%= time_ago_in_words(comment.created_at) %> ago</span></time>
      
      <div class="timeline-icon bg-success">
        <i class="entypo-suitcase"></i>
      </div>
      
      <div class="timeline-label">
        <h2>Commented on a <%= link_to_unless_current comment.post.class, comment.post %><%= simple_format comment.body %></h2>
        <p>added by <%= link_to comment.user.name, comment.user %> <strong>
        <%= pluralize(comment.likers(User).count, 'like')%></strong> 
        <% if comment.likers(User).count > 0 %>
        <% users= comment.likers(User) %>                 
          (<% for u in users %>| <%= link_to u.name, u %>
           <% end %>|)
        <% end %></p>
      </div>
    </div>
    
</article> 

<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h2 class="page-header">Post</h2>
<div class="row">
        <div class="[ col-xs-6 col-sm-offset-0 col-sm-8 ]">
            <div class="[ panel panel-default ] panel-google-plus">
            <div class="panel-heading">
                    <% if @post.user.avatar? %>
                    <img height="82" width="82" class="[ img-circle pull-left ]" src="<%= @post.user.avatar_url %>" />
                    <% else %>
                    <img height="82" width="82" class="[ img-circle pull-left ]" src="<%= @post.user.gravatar_url %>" />
                    <% end %>
                    <h3><%= link_to @post.user.name, @post.user %>
                    <div class="pull-right <%= @post.class %>-<%= @post.id %>">
                      <%= render 'shared/like_form', likeable: @post %>
                    <div style="float:left;" class="likes"><%= pluralize(@post.likers(User).count, 'like')%></div>
                    </div>
                    </h3>
                    <h5>
                    <% if @post.tags? %>
                      <strong>Tags:</strong>
                      <% @users = User.all %> 
                      <% tag=@post.tags.split(",") %>
                          <% tag.each do |t| %>
                          <% for user in @users %>
                            <% if t == user.name %>
                              <%= link_to t, user %>
                            <% end %>
                          <% end %>
                        <% end %>
                    <% end %>
                    <span class="pull-right"><%= time_ago_in_words(@post.created_at) %> ago</span> 
                    </h5>
                </div>
                <div class="panel-body">
                    <p><% if current_user.has_role? :admin or current_user.id == @post.user_id %>
                      <%= best_in_place @post, :content, :type => :textarea, :nil => "Click me to add content!" %><small><em>(click on the content to edit)</em></small>
                      <% else %>
                      <%= @post.content %>
                      <% end %><br>

                      <% if @post.avatar.present? %>
                        <% file = @post.avatar.url %>
                        <% extension = @post.avatar.file.extension.downcase %>

                        <% if %w{jpg png jpeg gif bmp tiff}.include?(extension) %>
                          <%= link_to image_tag(@post.avatar_url, :width => 500), @post.avatar_url %>
                        <% elsif %w{mp4 mov avi mpg mpeg flv}.include?(extension) %>
                          <%= link_to "play video", @post.avatar_url %>
                        <% elsif %w{mp3 wav}.include?(extension) %>
                          <%= link_to "play audio", @post.avatar_url %>
                        <% else %>
                          <%= link_to "download attatchment", @post.avatar_url %> Format:<%= extension %>
                        <% end %>
                      <% end %>
                    </p>
                </div>
            <div class="panel-footer">
                    <% if current_user.has_role? :admin or current_user.id == @post.user_id %>
                    <%= link_to '<button style="float:left;" type="button" class="[ btn btn-default ]"><span class="[ glyphicon glyphicon-trash ]" style="vertical-align:middle"></span></button>'.html_safe, @post, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
             <div class="input-placeholder">Add a comment...</div>
            </div>
            <div class="panel-google-plus-comment">
                    <% if current_user.avatar? %>
                    <img height="42" width="42" class="img-circle" src="<%= current_user.avatar_url %>" alt="User Image" />
                    <% else %>
                    <img height="42" width="42" class="img-circle" src="<%= current_user.gravatar_url %>" alt="User Image" />
                    <% end %>
                    <div class="panel-google-plus-textarea">
                        <textarea required="true" name="comment[body]" rows="4"></textarea>
                        <button type="submit" class="[ btn btn-success disabled ]">Post comment</button>
                        <button type="reset" class="[ btn btn-default ]">Cancel</button>
                    </div>
                    <div class="clearfix"></div>
                </div>

            </div>
        </div>
</div>

  <%= f.hidden_field :post_id %>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Comment</th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.id %></td>
        <td><%= comment.post_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>