config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'
  get 'messages/sent'

  get 'home/index'
  root :to => 'home#index' 

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'users/index'
  get 'users/show'
  get '/users/:id', :to => 'users#show', :as => :user
  get 'like' => 'users#like'
  get 'unlike' => 'users#unlike'

  get 'activities/index'
  get 'activities/user'

  resources :comments
  resources :posts
  resources :friendships
  resources :messages
  resources :contacts

  resources :gchats, only: [:new, :create, :index]
  get 'gchats/new'
  
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all
    redirect_to root_url
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
    redirect_to root_url
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
    redirect_to root_url
  end

  # GET /friendships/1/edit
  def edit
    redirect_to root_url
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])

    if @friendship.save
     redirect_to :back, notice: "Added friend."
    else
     redirect_to :back, notice: "Unable to add friend."
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    redirect_to :back, notice: "Removed friendship."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>