config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'
  get 'messages/sent'

  get 'home/index'
  root :to => 'home#index' 

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'users/index'
  get 'users/show'
  get '/users/:id', :to => 'users#show', :as => :user
  get 'like' => 'users#like'
  get 'unlike' => 'users#unlike'

  get 'activities/index'
  get 'activities/user'

  resources :comments
  resources :posts
  resources :friendships
  resources :messages
  resources :contacts

  resources :gchats, only: [:new, :create, :index]
  get 'gchats/new'
  
end

app/models/post.rb
class Post < ActiveRecord::Base
	resourcify
	
	belongs_to :user
	has_many :comments, dependent: :destroy

	mount_uploader :avatar, PictureUploader

	include PublicActivity::Model
	#tracked
	tracked owner: ->(controller, model) { controller && controller.current_user }
	
	acts_as_likeable

	default_scope -> { order('created_at DESC') }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /posts
  # GET /posts.json
  def index
    #@posts = Post.order("id DESC").all
    redirect_to root_url
    #@posts = current_user.posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.all
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
    redirect_to root_url
  end

  # GET /posts/1/edit
  def edit
    @post = current_user.posts.find(params[:id])
    redirect_to root_url
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to :back, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to :back, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    #@post = current_user.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :content, :avatar, :tags)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<h2 class="page-header">Status Upload</h2>
<div class="row"> 
    <div class="col-md-6">
                <div class="widget-area no-padding blank">
                <div class="status-upload">
                  <form action="/posts" method="post" enctype="multipart/form-data">
                    <textarea name="post[content]" required="true" placeholder="What are you doing right now?" ></textarea>
                    <ul>
                      <li><a data-toggle="tooltip" data-placement="bottom" data-original-title="Picture">
                      <div class="image-upload">
                      <label for="file-input1"><i class="fa fa-picture-o"></i>
                      </label>
                      <input type="file" id="file-input1" name="post[avatar]" accept="image/*" />
                      </div></a></li>
                      <li><a data-toggle="tooltip" data-placement="bottom" data-original-title="Audio">
                      <div class="image-upload">
                      <label for="file-input2"><i class="fa fa-music"></i>
                      </label>
                      <input type="file" id="file-input2" name="post[avatar]" accept="audio/*" />
                      </div></a></li>
                      <li><a data-toggle="tooltip" data-placement="bottom" data-original-title="Video">
                      <div class="image-upload">
                      <label for="file-input3"><i class="fa fa-video-camera"></i>
                      </label>
                      <input type="file" id="file-input3" name="post[avatar]" accept="video/*" />
                      </div></a></li>
                      <li><a data-toggle="tooltip" data-placement="bottom" data-original-title="File">
                      <div class="image-upload">
                      <label for="file-input4"><i class="fa fa-paperclip"></i>
                      </label>
                      <input type="file" id="file-input4" name="post[avatar]" />
                      </div></a></li>
                      <li>
                        <script>
                              $(document).ready(function() { $("#tag").select2({placeholder: "Tag user", allowClear: true}); });
                        </script>
                        <select style="width: 150px; padding-top: 8px;" id="tag" name="post[tags]" >
                                 <option value=""></option>
                              <% @users = User.all %>
                              <% @users.each do |u| %>
                                <% if current_user != u %>
                                <option value="<%= u.name %>"><%= u.name %></option>
                                <% end %>
                              <% end %>
                        </select>

                      </li>
                    </ul>
                    <button type="submit" class="btn btn-success green"><i class="fa fa-share"></i> Share</button>
                  </form>
                </div><!-- Status Upload  -->
              </div><!-- Widget Area -->
    </div>    
</div>

app/views/posts/_index.html.erb
<br><br><% @posts.each do |post| %>
<% if current_user.id == post.user.id || current_user.friendships.find_by_friend_id(post.user.id) %>
<div class="well">
    <div class="row">
<!-- posts -->
      <div class="media">
      <% if post.user.avatar? %>
      <a class="pull-left" href="<%= post.user.avatar_url %>">
        <img height="92" width="92" class="media-object" src="<%= post.user.avatar_url %>">
      </a>
      <% else %>
      <a class="pull-left" href="<%= post.user.gravatar_url %>">
        <img height="92" width="92" class="media-object" src="<%= post.user.gravatar_url %>">
      </a>
      <% end %>
      <div class="media-body">
          <p>
          <h4 style="float:left;" class="media-heading"><%= link_to post.user.name, post.user %></h4>
          
            <div style="padding-left: 790px;" class="<%= post.class %>-<%= post.id %>">
            <%= render 'shared/like_form', likeable: post %>
            <div class="likes"><%= pluralize(post.likers(User).count, 'like')%></div>
            </div>
          </p>
          <p>
            <% if current_user.has_role? :admin or current_user.id == post.user_id %>
            <%= best_in_place post, :content, :type => :textarea, :nil => "Click me to add content!" %><small><em>(click on the post to edit)</em></small>
            <% else %>
            <%= post.content %>
            <% end %>
          </p>
          <% if post.avatar.present? %>

              <% file = post.avatar.url %>
              <% extension = post.avatar.file.extension.downcase %>

              <% if %w{jpg png jpeg gif bmp tiff}.include?(extension) %>
                <%= link_to image_tag(post.avatar_url, :width => 500), post.avatar_url %>
              <% elsif %w{mp4 mov avi mpg mpeg flv}.include?(extension) %>
                <%= link_to "play video", post.avatar_url %>
              <% elsif %w{mp3 wav}.include?(extension) %>
                <%= link_to "play audio", post.avatar_url %>
              <% else %>
                <%= link_to "download attatchment", post.avatar_url %> <%= extension %>
              <% end %>
              <br><br>
          <% end %>
      <ul class="list-inline list-unstyled">
        <li><span><i class="glyphicon glyphicon-calendar"></i> <small><em><%= time_ago_in_words(post.created_at) %> ago </em>(<%= post.created_at.to_time.to_formatted_s(:db) %>)</small> </span></li>
            <% if current_user.has_role? :admin or current_user.id == post.user_id %>
            <li>|</li>
            <span><i class="glyphicon glyphicon-trash"></i> 
              <!-- <%# link_to 'Edit', edit_post_path(post) %> -->
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </span>
            <% end %>
            <li>
               <% if post.tags? %>
               <li>|</li>
               <span title="Tags" class="glyphicon glyphicon-tags"></span>
                 <% for user in @users %>
                 <% if post.tags == user.name %>
                 <%=link_to post.tags, user %>
                 <% end %>
                 <% end %>
                 <% end %>
            </li>
      </ul>
       </div>
       </div>
<!-- comments -->
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-comment"></span> Comments
                    <div class="pull-right label label-warning">
                        <%= pluralize(post.comments.count, 'comment') %>
                    </div>
                </div>
                <% if post.comments.count > 0 %>
                <div class="panel-body1">
                    <ul class="chat">
                    <% post.comments.each do |comment| %>
                        <li class="right clearfix"><span class="chat-img pull-right">
                          <% if comment.user.avatar? %>
                            <img height="42" width="42" src="<%= comment.user.avatar %>" alt="User Avatar" class="img-circle" />
                          <% else %>
                            <img height="42" width="42" src="<%= comment.user.gravatar_url %>" alt="User Avatar" class="img-circle" />
                          <% end %>
                        </span>
                            <div class="chat-body clearfix">
                                <div class="header">
                                    <small class=" text-muted"><span class="glyphicon glyphicon-time"></span><%= time_ago_in_words(comment.created_at) %> ago</small>
                                    <div class="pull-right primary-font text-muted">By: 
                                    <strong><%= link_to comment.user.name, comment.user %></strong>
                                    </div>
                                </div>
                                <p>
                                  <% if current_user.has_role? :admin or current_user.id == comment.user_id %>
                                  <%= best_in_place comment, :body, :type => :textarea, :nil => "Click me to add content!" %><small><em>(click on the comment to edit)</em></small>
                                  <% else %>
                                  <%= comment.body %>
                                  <% end %>
                                </p>
                            </div>
                            <div class="<%= comment.class %>-<%= comment.id %>">
                            <%= render 'shared/like_form', likeable: comment %>
                            <div style="float:left;" class="likes"><%= pluralize(comment.likers(User).count, 'like')%></div>
                            </div>
                            <% if current_user.has_role? :admin or current_user.id == comment.user_id %>
                            <%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?'}, :class=>'pull-right' %>
                            <%# link_to 'Edit', edit_comment_path(comment) %>
                            <% end %>
                        </li>
                    <% end %>
                    </ul>
                </div>
                <% end %>
                <div class="panel-footer">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <%= link_to '<button style="width:920px;" class="btn btn-warning btn-sm" id="btn-chat">
                                New Comment</button>'.html_safe, post %>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<% end %>
<% end %>

app/views/posts/_post.html.erb
<%= div_for post do %>

  <article class="timeline-entry left-aligned">
    
    <div class="timeline-entry-inner">
      <time class="timeline-time" ><span><%= time_ago_in_words(post.created_at) %> ago</span></time>
      
      <div class="timeline-icon bg-secondary">
        <i class="entypo-suitcase"></i>
      </div>
      
      <div class="timeline-label">
        <h2>Added a <%= link_to_unless_current post.class, post %><%= simple_format post.content %>

        <% if post.avatar.present? %>

              <% file = post.avatar.url %>
              <% extension = post.avatar.file.extension.downcase %>

              <% if %w{jpg png jpeg gif bmp tiff}.include?(extension) %>
                <%= link_to "view image", post.avatar_url %>
              <% elsif %w{mp4 mov avi mpg mpeg flv}.include?(extension) %>
                <%= link_to "play video", post.avatar_url %>
              <% elsif %w{mp3 wav}.include?(extension) %>
                <%= link_to "play audio", post.avatar_url %>
              <% else %>
                <%= link_to "download attatchment", post.avatar_url %> <%= extension %>
              <% end %>
              
        <% end %></h2>

        <p>added by <%= link_to post.user.name, post.user %> <strong><%= link_to pluralize(post.comments.count, 'comment'), post %>
        <%= pluralize(post.likers(User).count, 'like')%></strong> 
        <% if post.likers(User).count > 0 %>
          <% users= post.likers(User) %>                 
          (<% for u in users %>| <%= link_to u.name, u %>
           <% end %>|)
        <% end %></p>
      </div>
    </div>
    
  </article>  

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container-fluid main-container">
<%= render "layouts/sidenav" %>
<div class="col-md-10 content">

<!-- post -->
<%= render 'comments/form' %>

<!-- comments -->
            <div class="row">
                <div class="[ col-xs-6 col-sm-offset-0 col-sm-8 ]">   
                  <div class="page-header">
                    <h3><small class="pull-right">
                    <%=  pluralize(@post.comments.count, 'comment') %></small> Comments </h3>
                  </div> 
                   <div class="comments-list">
                    <% @comments.each do |comment| %>
                       <div class="right media">
                           <p class="pull-right"><small><%= time_ago_in_words(comment.created_at) %> ago</small>
                           <br>
                           <% if current_user.has_role? :admin or current_user.id == comment.user_id %>
                                   <%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %>
                                   <%# link_to 'Edit', edit_comment_path(comment) %>
                           <% end %>
                           </p>
                            <a class="media-left">
                              <% if comment.user.avatar? %>
                              <img class="img-circle" height="42" width="42" src="<%= comment.user.avatar %>">
                              <% else %>
                              <img class="img-circle" height="42" width="42" src="<%= comment.user.gravatar_url %>">
                              <% end %>
                            </a>
                            <div class="media-body">
                                
                              <h4 class="media-heading user_name"><%= link_to comment.user.name,comment.user %></h4>
                              <% if current_user.has_role? :admin or current_user.id == comment.user_id %>
                                <%= best_in_place comment, :body, :type => :textarea, :nil => "Click me to add content!" %><small><em>(click on the content to edit)</em></small>
                              <% else %>
                                <%= comment.body %>
                              <% end %>
                                  <div class="<%= comment.class %>-<%= comment.id %>">
                                  <%= render 'shared/like_form', likeable: comment %>
                                  <div class="likes"><%=
                                   pluralize(comment.likers(User).count, 'like') %></div>
                                  </div>
                            </div>
                          </div>
                    <% end %>
                   </div>  
                </div>
            </div>

<%# if current_user.id == @post.user_id %>
<%# link_to 'Edit', edit_post_path(@post) %>
<%# end %>
<%# link_to 'Back', posts_path %>

</div>
</div>